### ISSUE TITLE
GTK Window Extents are still wonky

### ISSUE THREAD

**Issue by fedoranvar** [vaxerski/Hyprland#117]
Good day to you!

i've noticed weird behaviour in applications such as: `wdisplays`, `swappy`

for example , `wdisplays`

1. there is some blurred  rectangle area around window
2. if i want to click to `dont rotate` i need to move cursor to red-circle are 
3. i can move cursor in blurred rectangle area and not loosing focus on this window

for me it's looks like areas for interaction with program and visible ui of program are mismatching 

![image](https://user-images.githubusercontent.com/52028706/170836802-b22e7f9f-f561-4ac4-b552-c3c86d50baa2.png)

**Comment by vaxerski** [comment]
That's an issue with GTK window extents. I've mostly fixed them, but it seems not fully. The fact that your mouse offset is wrong is weird. That should be fixed. The border though, expected.

The thing is that either the theme forced by the app, or your system GTK theme draws shadows on the window surface.

Imho, that should be criminally illegal, but GTK devs thought otherwise.

I'll test the system more in the future.

**Comment by vaxerski** [comment]
cursor offset fixed in 08e0567d3ae348f950aacbb734ead61b0d8eebe1

was just a typo.

The shadow and the window being small will be fixed in the future.

**Comment by frigaut** [comment]
Cursor offset indeed fixed for me in 08e0567 - thanks @vaxerski 

The issue with the box-shadow persist of course. I know you advise to edit the gtk-4.0 css and set windows box-shadow to none.
Alternatively, would you have a recommendation for a gtk theme that works out of the box (read: does not exhibit this)?
And thanks a bunch, absolutely fantastic work with hyprland. Been riding it for a couple of days. I will soon fill in a couple of bug reports :-)

**Comment by fedoranvar** [comment]
updated to recent build `d2e189`  - issue with cursor still persist

**Comment by vaxerski** [comment]
it's been fixed, are you sure you updated? Please do `hyprctl version` to verify.

**Comment by frigaut** [comment]
@fedoranvar can you provide an example of app/theme where you see the cursor offset issue? I don't see it any more.

**Comment by fedoranvar** [comment]
@vaxerski 
i'm building from flake, so 
![image](https://user-images.githubusercontent.com/52028706/170929397-34438055-1f89-4044-9845-1195cfccfecb.png), 

@frigaut 

still `wdisplays`, `swappy`

checked on recent commit (https://github.com/vaxerski/Hyprland/commit/2de65771eaa8864c7901b436808f892c00c0c1ba) - a

**Comment by frigaut** [comment]
OK, I think I've got it. Partially.
As @vaxerski hinted in in the hpyrland FAQ, you've got to add some css in your gtk-3.0/gtk*.css and gtk-4.0/gtk*.css (I've copied mine in my ~/.themes, I am using Catppuccin-blue:
```css
decoration, decoration:backdrop, window {
  box-shadow: none;
  border: none;
  margin: 0;
}
```
after that, you may have to logout (not sure reloading the theme does it).
This, plus the patched hyprland as per the above posts, works for me for the following gtk applications. When I say "works for me", I mean no cursor offset, and no funky border gap around windows. Tested on wdisplays, baobab, guvcview, eog, cheese, gnome-disks, gthumb, gimp, inkscape main window, nautilus.

Some other still exhibit the issue (both cursor offset and wide border gaps), for instance gnome-control-center (which seems to be using Adwaita regardless of your selected theme), and e.g. inkscape greeter.

Note that I am using nwg-look to set my theme, but I don't think this is important, probably works as well using lxappearance.

![image](https://user-images.githubusercontent.com/613346/170970304-c937e5e5-dae9-4a38-9691-aca430a1c1f3.png)

**Comment by frigaut** [comment]
Just to prove what I am saying:

https://user-images.githubusercontent.com/613346/170972741-aa4a1d6a-04bf-40be-bef1-dce0c856b26f.mp4

**Comment by fedoranvar** [comment]
@frigaut 
your advice helped
thank you! 

for NixOS users:

i've added 
```nix
gtk.gtk3.extraCss = "
decoration, decoration:backdrop, window {
  box-shadow: none;
  border: none;
  margin: 0;
}
";
```
to my `home-manager`
