### ISSUE TITLE
[maybe nvidia] Transparency

### ISSUE THREAD

**Issue by niwheeler07** [vaxerski/Hyprland#41]
Transparency+blur doesn't work with teminal or gtk apps, they're just clear. It works fine with firefox. The gtk apps have a rendering error where they have a big clear border, and that border is blurred, but the apps themselves aren't. They're all just plain clear. I'll be able to talk in like five hours because I gotta go somewhere. It doesn't matter which one is active, if you're wondering

**Comment by vaxerski** [comment]
demo video or app name please

**Comment by niwheeler07** [comment]
I've not got obs working on wayland yet, I'll send a video when I do. Whenevr I try to attach something to this issue by dragging and dropping, firefox immediately closes.

**Comment by niwheeler07** [comment]
nvidia+obs+wayland are incompatible apparently
firefox is in wayland mode

**Comment by niwheeler07** [comment]
I will try to take a pic of the screen with an external camera

**Comment by vaxerski** [comment]
nvidia + obs + wayland work afaik if you use pipewire screen sharing, explained in the discord server

**Comment by niwheeler07** [comment]
I don't have discord, but I tried pipewire and it just doesn't show up

**Comment by vaxerski** [comment]
I'll repost them onto the wiki then

**Comment by niwheeler07** [comment]
Ok thanks so much

**Comment by vaxerski** [comment]
https://github.com/vaxerski/Hyprland/wiki/FAQ

**Comment by vaxerski** [comment]
ah ok, can fix

**Comment by niwheeler07** [comment]
cool. See what I mean about the gtk apps? they're all wonky

**Comment by vaxerski** [comment]
if by wonky you mean no blur, then yes

**Comment by niwheeler07** [comment]
but they are smaller than their borders

**Comment by niwheeler07** [comment]
and for example in nautilus you cannot click where it show the folders, you have to click to the left of them

**Comment by vaxerski** [comment]
That's a GTK issue, and it's related to your theme. Some themes extend the borders meaning it will look like that. You need to edit your theme and remove all border extension and shadow effects for windows. When it comes to clicking to the left etc, a resize of the app should fix it by refreshing the window info.

**Comment by niwheeler07** [comment]
the bigger the app, the bigger the offset is. resizing doesn't fix it. I'll try changing those theme options though

**Comment by niwheeler07** [comment]
cool let me update really quick and i'll be back

**Comment by niwheeler07** [comment]
now the background is blinding white and I cannot change it

**Comment by vaxerski** [comment]
oh shit oops

**Comment by niwheeler07** [comment]
now the background is blinding white and I cannot change it

**Comment by niwheeler07** [comment]
oops sorry

**Comment by vaxerski** [comment]
fixed

**Comment by niwheeler07** [comment]
cool now it works

**Comment by vaxerski** [comment]
great, the mouse problems are probably due to the borders being extended. If you find where the setting is, lmk too as some of my windows also do that and it's super annoying.

Closing then :)

**Comment by vaxerski** [comment]
found it for mine, go to your theme's `gtk-4.0` folder, and in all CSS files in the root, find `window {` and make all the `border` and `box-shadow` fields to `none`

**Comment by niwheeler07** [comment]
Thanks!

**Comment by phisch** [comment]
@vaxerski the gtk issue looks to me like it is related to `_GTK_FRAME_EXTENTS`.
On x11 gtk checks if the window manager supports it, and if it reports support, gtk will draw shadows, possibly rounded corners and some other stuff. The window will get the `_GTK_FRAME_EXTENTS` atom that contains the real size the window should have, so you have to position the window accordingly.

I am not certain how this is handled on wayland, but you might want to look into this, otherwise you will have a lot of issues with GTK in the future.

**Comment by vaxerski** [comment]
@phisch it's weird. Can't find much code regarding that in sway or wayfire. it's not an XDG deco, and the surface doesn't really seem to contain some extents, unless I am blind. Any clues? You can also open a new issue we could talk there.

**Comment by phisch** [comment]
@vaxerski I was just mentioning it because I randomly read this ticket. Not even using the project, just thought it looks interesting (so keep it up).

You have to explicitly support `_GTK_FRAME_EXTENTS` for gtk to draw shadows and those enlarged "border" areas. I think sway for example doesn't do this, which is why GTK windows on sway probably have no shadows. My guess would be that you do report some capability, which tells GTK to enable this. But I don't actually know how this works on wayland, maybe it's completely different there, only got frustrated with it on x11.

**Comment by vaxerski** [comment]
X11 works like this. Definitely not wayland. Hyprland does not broadcast such support (as you don't do that at all on wayland) and thus XWayland apps work properly, and do not get their shadows applied. I will have to dig deeper into this, it seems.

**Comment by vaxerski** [comment]
fixed extents with mouse. fixing them visually is a lower prio.
